// Mocks generated by Mockito 5.4.6 from annotations
// in chat_flutter/test/presentation/auth/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chat_core/src/core/failures.dart' as _i5;
import 'package:chat_core/src/domain/entities/user.dart' as _i6;
import 'package:chat_core/src/domain/repositories/auth_repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
    _i2.Either<
      _i5.Failure,
      ({String accessToken, String refreshToken, _i6.User user})
    >
  >
  register({
    required String? username,
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.Failure,
                    ({String accessToken, String refreshToken, _i6.User user})
                  >
                >.value(
                  _FakeEither_0<
                    _i5.Failure,
                    ({String accessToken, String refreshToken, _i6.User user})
                  >(
                    this,
                    Invocation.method(#register, [], {
                      #username: username,
                      #email: email,
                      #password: password,
                      #displayName: displayName,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<
              _i5.Failure,
              ({String accessToken, String refreshToken, _i6.User user})
            >
          >);

  @override
  _i4.Future<
    _i2.Either<
      _i5.Failure,
      ({String accessToken, String refreshToken, _i6.User user})
    >
  >
  login({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.Failure,
                    ({String accessToken, String refreshToken, _i6.User user})
                  >
                >.value(
                  _FakeEither_0<
                    _i5.Failure,
                    ({String accessToken, String refreshToken, _i6.User user})
                  >(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<
              _i5.Failure,
              ({String accessToken, String refreshToken, _i6.User user})
            >
          >);

  @override
  _i4.Future<
    _i2.Either<_i5.Failure, ({String accessToken, String refreshToken})>
  >
  refreshToken({required String? refreshToken}) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {#refreshToken: refreshToken}),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.Failure,
                    ({String accessToken, String refreshToken})
                  >
                >.value(
                  _FakeEither_0<
                    _i5.Failure,
                    ({String accessToken, String refreshToken})
                  >(
                    this,
                    Invocation.method(#refreshToken, [], {
                      #refreshToken: refreshToken,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, ({String accessToken, String refreshToken})>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User?>>.value(
              _FakeEither_0<_i5.Failure, _i6.User?>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User?>>);
}
