// Mocks generated by Mockito 5.4.6 from annotations
// in chat_flutter/test/presentation/messages/message_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chat_core/src/core/failures.dart' as _i5;
import 'package:chat_core/src/domain/entities/message.dart' as _i6;
import 'package:chat_core/src/domain/repositories/message_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i3.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Message>> sendMessage(
    String? channelId, {
    required String? text,
    String? parentId,
    String? idempotencyKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [channelId],
              {
                #text: text,
                #parentId: parentId,
                #idempotencyKey: idempotencyKey,
              },
            ),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Message>>.value(
              _FakeEither_0<_i5.Failure, _i6.Message>(
                this,
                Invocation.method(
                  #sendMessage,
                  [channelId],
                  {
                    #text: text,
                    #parentId: parentId,
                    #idempotencyKey: idempotencyKey,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Message>>);

  @override
  _i4.Future<
    _i2.Either<_i5.Failure, ({List<_i6.Message> messages, String? nextCursor})>
  >
  getMessages(
    String? channelId, {
    String? cursor,
    int? limit = 50,
    String? direction = 'before',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [channelId],
              {#cursor: cursor, #limit: limit, #direction: direction},
            ),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.Failure,
                    ({List<_i6.Message> messages, String? nextCursor})
                  >
                >.value(
                  _FakeEither_0<
                    _i5.Failure,
                    ({List<_i6.Message> messages, String? nextCursor})
                  >(
                    this,
                    Invocation.method(
                      #getMessages,
                      [channelId],
                      {#cursor: cursor, #limit: limit, #direction: direction},
                    ),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<
              _i5.Failure,
              ({List<_i6.Message> messages, String? nextCursor})
            >
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Message>> updateMessage(
    String? channelId,
    String? messageId, {
    required String? text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateMessage,
              [channelId, messageId],
              {#text: text},
            ),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Message>>.value(
              _FakeEither_0<_i5.Failure, _i6.Message>(
                this,
                Invocation.method(
                  #updateMessage,
                  [channelId, messageId],
                  {#text: text},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Message>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMessage(
    String? channelId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [channelId, messageId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteMessage, [channelId, messageId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<
    _i2.Either<_i5.Failure, ({List<_i6.Message> messages, String? nextCursor})>
  >
  getThreadMessages(
    String? channelId,
    String? parentId, {
    String? cursor,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getThreadMessages,
              [channelId, parentId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.Failure,
                    ({List<_i6.Message> messages, String? nextCursor})
                  >
                >.value(
                  _FakeEither_0<
                    _i5.Failure,
                    ({List<_i6.Message> messages, String? nextCursor})
                  >(
                    this,
                    Invocation.method(
                      #getThreadMessages,
                      [channelId, parentId],
                      {#cursor: cursor, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<
              _i5.Failure,
              ({List<_i6.Message> messages, String? nextCursor})
            >
          >);
}
