// Mocks generated by Mockito 5.4.6 from annotations
// in chat_flutter/test/presentation/channels/create_channel_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chat_core/src/core/failures.dart' as _i5;
import 'package:chat_core/src/domain/entities/channel.dart' as _i8;
import 'package:chat_core/src/domain/entities/membership.dart' as _i9;
import 'package:chat_core/src/domain/entities/user.dart' as _i6;
import 'package:chat_core/src/domain/repositories/channel_repository.dart'
    as _i7;
import 'package:chat_core/src/domain/repositories/user_repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> getMe() =>
      (super.noSuchMethod(
            Invocation.method(#getMe, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#getMe, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> updateProfile({
    String? displayName,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#updateProfile, [], {
                  #displayName: displayName,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#getUser, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.User>>> searchUsers(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.User>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.User>>(
                    this,
                    Invocation.method(#searchUsers, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.User>>>);
}

/// A class which mocks [ChannelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelRepository extends _i1.Mock implements _i7.ChannelRepository {
  MockChannelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>> createChannel({
    required _i8.ChannelType? type,
    String? name,
    String? description,
    required List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChannel, [], {
              #type: type,
              #name: name,
              #description: description,
              #memberIds: memberIds,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>>.value(
              _FakeEither_0<_i5.Failure, _i8.Channel>(
                this,
                Invocation.method(#createChannel, [], {
                  #type: type,
                  #name: name,
                  #description: description,
                  #memberIds: memberIds,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>> getChannel(
    String? channelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChannel, [channelId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>>.value(
              _FakeEither_0<_i5.Failure, _i8.Channel>(
                this,
                Invocation.method(#getChannel, [channelId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>>);

  @override
  _i4.Future<
    _i2.Either<_i5.Failure, ({List<_i8.Channel> channels, String? nextCursor})>
  >
  listChannels({String? cursor, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#listChannels, [], {
              #cursor: cursor,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.Failure,
                    ({List<_i8.Channel> channels, String? nextCursor})
                  >
                >.value(
                  _FakeEither_0<
                    _i5.Failure,
                    ({List<_i8.Channel> channels, String? nextCursor})
                  >(
                    this,
                    Invocation.method(#listChannels, [], {
                      #cursor: cursor,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<
              _i5.Failure,
              ({List<_i8.Channel> channels, String? nextCursor})
            >
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>> updateChannel(
    String? channelId, {
    String? name,
    String? description,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateChannel,
              [channelId],
              {#name: name, #description: description, #avatarUrl: avatarUrl},
            ),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>>.value(
              _FakeEither_0<_i5.Failure, _i8.Channel>(
                this,
                Invocation.method(
                  #updateChannel,
                  [channelId],
                  {
                    #name: name,
                    #description: description,
                    #avatarUrl: avatarUrl,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Channel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteChannel(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChannel, [channelId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteChannel, [channelId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Membership>> addMember(
    String? channelId, {
    required String? userId,
    required _i9.MemberRole? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addMember,
              [channelId],
              {#userId: userId, #role: role},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i9.Membership>(
                    this,
                    Invocation.method(
                      #addMember,
                      [channelId],
                      {#userId: userId, #role: role},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeMember(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [channelId, userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeMember, [channelId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Membership>>> getMembers(
    String? channelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, [channelId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Membership>>(
                    this,
                    Invocation.method(#getMembers, [channelId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Membership>>>);
}
