// Mocks generated by Mockito 5.4.6 from annotations
// in tuna_chat_flutter/test/presentation/connection/connection_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tuna_chat/src/core/failures.dart' as _i5;
import 'package:tuna_chat/src/domain/entities/user.dart' as _i6;
import 'package:tuna_chat/src/domain/repositories/connection_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConnectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionRepository extends _i1.Mock
    implements _i3.ConnectionRepository {
  MockConnectionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.User? get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValueForMissingStub: null,
          )
          as _i6.User?);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> connectUser({
    required String? userId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectUser, [], {
              #userId: userId,
              #token: token,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#connectUser, [], {
                  #userId: userId,
                  #token: token,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> disconnectUser() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectUser, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#disconnectUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
